
INSERT IGNORE INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(1, 'Uncategorized', 'uncategorized', 0),
(2, 'simple', 'simple', 0),
(3, 'grouped', 'grouped', 0),
(4, 'variable', 'variable', 0),
(5, 'external', 'external', 0),
(6, 'exclude-from-search', 'exclude-from-search', 0),
(7, 'exclude-from-catalog', 'exclude-from-catalog', 0),
(8, 'featured', 'featured', 0),
(9, 'outofstock', 'outofstock', 0),
(10, 'rated-1', 'rated-1', 0),
(11, 'rated-2', 'rated-2', 0),
(12, 'rated-3', 'rated-3', 0),
(13, 'rated-4', 'rated-4', 0),
(14, 'rated-5', 'rated-5', 0),
(15, 'Uncategorized', 'uncategorized', 0),
(16, 'Air Conditioning', 'air-conditioning', 0),
(17, 'Airport Transport', 'airport-transport', 0),
(18, 'Business', 'business', 0),
(19, 'Charming', 'charming', 0),
(20, 'Classic', 'classic', 0),
(21, 'Fitness Center', 'fitness-center', 0),
(22, 'Flat Tv', 'flat-tv', 0),
(23, 'Green', 'green', 0),
(24, 'Heater', 'heater', 0),
(25, 'Internet – Wifi', 'internet-wifi', 0),
(26, 'Luxury', 'luxury', 0),
(27, 'Parking', 'parking', 0),
(28, 'Pool', 'pool', 0),
(29, 'Quaint', 'quaint', 0),
(30, 'Quite', 'quite', 0),
(31, 'Restaurant', 'restaurant', 0),
(32, 'Romantic', 'romantic', 0),
(33, 'Smoking Room', 'smoking-room', 0),
(34, 'Spa &amp; Sauna', 'spa-sauna', 0),
(35, 'Standard', 'standard', 0),
(36, 'Washer &amp; Dryer', 'washer-dryer', 0),
(37, 'Mid-range', 'mid-range', 0),
(38, 'Party', 'party', 0),
(39, 'Best value', 'best-value', 0),
(40, 'Boutique', 'boutique', 0),
(41, 'Budget', 'budget', 0),
(42, 'Trendy', 'trendy', 0),
(43, 'Cultural events', 'cultural-events', 0),
(44, 'Tiptoe', 'tiptoe', 0),
(45, 'Tulips', 'tulips', 0),
(46, 'Washington', 'washington', 0),
(47, 'Carnivals', 'carnivals', 0),
(48, 'Gallery', 'post-format-gallery', 0),
(49, 'Mountains', 'mountains', 0),
(50, 'National', 'national', 0),
(51, 'Parks', 'parks', 0),
(52, 'beaches', 'beaches', 0),
(53, 'Beauty', 'beauty', 0),
(54, 'Cultural', 'cultural', 0),
(55, 'Museums', 'museums', 0),
(56, 'National parks', 'national-parks', 0),
(57, 'Beauty beaches', 'beauty-beaches', 0),
(58, 'Mountains', 'mountains', 0),
(59, 'Museums', 'museums', 0),
(60, 'Image', 'post-format-image', 0),
(61, 'Parks and Carnivals', 'parks-and-carnivals', 0),
(62, 'Air Conditioning', 'air-conditioning', 0),
(63, 'Flat Screen TV', 'flat-screen-tv', 0),
(64, 'Hair dryer', 'bathtub', 0),
(65, 'Hot water', 'terrace', 0),
(66, 'Kitchen', 'patio', 0),
(67, 'Queen Room', 'queen-room', 0),
(68, 'Shampoo', 'soundproof', 0),
(69, 'Wifi', 'mini-bar', 0),
(70, 'Deluxe', 'deluxe', 0),
(71, 'Normal', 'normal', 0),
(72, 'Standard Double-Double Room', 'standard-double-double-room', 0),
(73, 'Standard Room', 'standard-room', 0),
(74, 'Family Suite', 'family-suite', 0),
(75, 'City trips', 'city-trips', 0),
(76, 'Ecotourism', 'ecotourism', 0),
(77, 'Escorted Tour', 'escorted-tour', 0),
(78, 'Group Tour', 'group-tour', 0),
(79, 'Ligula', 'ligula', 0),
(80, 'Hosted tours', 'hosted-tours', 0),
(81, '[Mega] Listing Activity', 'mega-listing-activity', 0),
(82, '[Mega] Listing Hotel', 'mega-listing-hotel', 0),
(83, '[Mega] Listing Tour', 'mega-listing-tour', 0),
(84, '[Mega] Single Activity', 'mega-single-activity', 0),
(85, '[Mega] Single Hotel', 'mega-single-hotel', 0),
(86, '[Mega] Single House', 'mega-single-house', 0),
(87, '[Mega] Single Tour', 'mega-single-tour', 0),
(88, 'Footer New', 'footer-new', 0),
(89, 'Footer New 2', 'footer-new-2', 0),
(90, 'Hotel Menu', 'hotel-menu', 0),
(91, 'Air Conditioning', 'air-conditioning', 0),
(92, 'Breakfast', 'breakfast', 0),
(93, 'Elder Access', 'elder-access', 0),
(94, 'For Children', 'for-children', 0),
(95, 'Kitchen', 'kitchen', 0),
(96, 'No Smoking', 'smoking-allowed', 0),
(97, 'Parking', 'parking', 0),
(98, 'Pet Allowed', 'pet-allowed', 0),
(99, 'Pool', 'pool', 0),
(100, 'Wheelchair Access', 'wheelchair-access', 0),
(101, 'Wi-Fi Internet', 'wi-fi-internet', 0),
(102, 'Airbag', 'airbag', 0),
(103, 'Convertibles', 'convertibles', 0),
(104, 'Coupes', 'coupes', 0),
(105, 'FM Radio', 'fm-radio', 0),
(106, 'Hatchbacks', 'hatchbacks', 0),
(107, 'Minivans', 'minivans', 0),
(108, 'Power Windows', 'power-windows', 0),
(109, 'Sedan', 'sedan', 0),
(110, 'Sensor', 'sensor', 0),
(111, 'Speed Km', 'speed-km', 0),
(112, 'Steering Wheel', 'steering-wheel', 0),
(113, 'SUVs', 'suvs', 0),
(114, 'Trucks', 'trucks', 0),
(115, 'Wagons', 'wagons', 0);
